# FROM python:3.9-slim
FROM python:3.7-slim

WORKDIR /app
COPY ./requirements.txt /app

RUN pip3 --no-cache-dir --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org install -r requirements.txt

RUN apt-get update \
    && apt-get install -y build-essential patchelf libpython3.7

WORKDIR /app/src

# 設定時區
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT /bin/sh